import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, BarChart3, Check, ChevronRight, CircleAlert, Clock3, Compass, Fuel, Gauge, MapPin, Plus, Ship, ShieldCheck, TrendingUp, Waves } from "lucide-react";
import { PrototypeButton } from "@/components/ui/prototype-button";
import { compactMoney, evaluate, money, origins, ports } from "@/lib/chartering";
import { decisionInsights } from "@/lib/decision-insights";
import { DataAssumptions, ScheduleLens } from "@/components/PlanningAids";
import { illustrativeOutlook } from "@/lib/planning-aids";
import { useScenario } from "@/lib/scenario-context";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export const Route = createFileRoute("/dashboard")({
  head: () => ({ meta: [{ title: "Decision Dashboard — Charterwise" }, { name: "description", content: "Explore illustrative freight outlooks, vessel feasibility, voyage costs and contract options for an East Coast coal shipment." }, { property: "og:title", content: "Decision Dashboard — Charterwise" }, { property: "og:description", content: "An explainable view of freight risk, port fit, vessel costs and chartering choices." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Dashboard,
});
function Dashboard() {
  const { scenario, setScenario, hasRun } = useScenario();
  const data = evaluate(scenario);
  const insight = decisionInsights(scenario);
  const chartData = illustrativeOutlook(scenario);
  const eligible = data.rows.filter(r => r.feasible).length;
  return <div className="bg-secondary min-h-[calc(100vh-72px)] pb-20">
    <div className="border-b border-border bg-background"><div className="shell py-9 md:py-12"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><div className="eyebrow">DECISION WORKSPACE / OVERVIEW</div><h1 className="mt-3 font-display text-3xl font-bold md:text-4xl">Chartering dashboard</h1><p className="mt-3 text-sm text-muted-foreground">An end-to-end view of the decision, from market signal to voyage recommendation.</p></div><PrototypeButton asChild size="lg" className="h-11"><Link to="/new-analysis"><Plus/> New analysis</Link></PrototypeButton></div></div></div>
    <div className="shell pt-8">
      <div className="mb-7 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span className="font-semibold text-foreground">{hasRun ? "Your latest scenario" : "Illustrative scenario"}</span><ChevronRight size={13}/><span>{data.origin.name} → {data.port.name}</span><span className="ml-auto border border-border bg-card px-2 py-1 uppercase font-bold tracking-wider">Illustrative estimates · not live data</span></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric icon={TrendingUp} label="MARKET DIRECTION" value="Upward" detail={`+${(data.trend*100).toFixed(1)}% indicative · ${data.horizon} days`} accent/>
        <Metric icon={Ship} label="FEASIBLE VESSELS" value={`${eligible} of 3`} detail={`${data.port.name} physical limits checked`}/>
        <Metric icon={BarChart3} label="LOWEST VOYAGE COST" value={data.best ? `$${data.best.perTonne.toFixed(2)}/t` : "—"} detail={data.best ? `${data.best.name} · ${compactMoney(data.best.total)} total` : "Try another port"}/>
        <Metric icon={Gauge} label="RISK PROFILE" value={data.riskLevel} detail={`Input setting ${data.risk}/100 · not measured volatility`}/>
      </div>
      <div className="mt-7 grid gap-5 xl:grid-cols-[1.45fr_1fr]">
        <div className="panel p-6 md:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow">01 / MARKET OUTLOOK</div><h2 className="mt-2 font-display text-xl font-bold">Freight direction & uncertainty</h2><p className="mt-2 text-sm text-muted-foreground">Indexed illustration, baseline = 100. Uses the same direction assumption as the report.</p></div><div className="flex border border-border bg-secondary p-1">{[30,60,90].map(n => <PrototypeButton key={n} size="sm" variant={scenario.horizon === n ? "default" : "ghost"} className="h-7 px-3 text-xs" onClick={() => setScenario({ ...scenario, horizon:n })}>{n}d</PrototypeButton>)}</div></div><div className="mt-7 h-62 w-full min-w-0"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ left: -25, right: 8, top: 8, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="day" tick={{ fill:"var(--muted-foreground)", fontSize:11 }} axisLine={false} tickLine={false}/><YAxis domain={[80, 140]} tick={{ fill:"var(--muted-foreground)", fontSize:11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ border:"1px solid var(--border)", background:"var(--card)", borderRadius:4, color:"var(--foreground)" }} formatter={(v, name) => [v, name === "value" ? "Illustrative direction" : name]}/><Area dataKey="value" stroke="var(--accent)" fill="var(--accent)" fillOpacity={.1} strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><CircleAlert size={14}/> Direction is a demo assumption, not a trained forecast or live Baltic index.</div></div>
        <div className="panel flex flex-col p-6 md:p-7"><div className="eyebrow">02 / DECISION SIGNAL</div><h2 className="mt-2 font-display text-xl font-bold">What should we do?</h2><div className="mt-7 border-l-3 border-accent bg-secondary p-5"><div className="text-xs font-bold uppercase tracking-wider text-accent">Illustrative recommendation</div><div className="mt-2 font-display text-3xl font-bold">{data.action}</div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{data.best ? `${data.best.name} is the lowest-cost feasible vessel for ${data.quantity.toLocaleString()} tonnes via ${data.port.name}.` : "No vessel class fits the selected port. Explore another destination."}</p></div><div className="mt-6 space-y-4 text-sm"><div className="flex items-center gap-3"><ShieldCheck size={18} className="text-accent"/><span>Hard-filtered by draft, LOA & beam</span></div><div className="flex items-center gap-3"><Clock3 size={18} className="text-accent"/><span>{data.port.wait} assumed waiting days priced in</span></div><div className="flex items-center gap-3"><Waves size={18} className="text-accent"/><span>Spot versus longer contracts compared</span></div></div><PrototypeButton asChild variant="outline" className="mt-auto w-full pt-0 translate-y-3"><Link to="/results">View full decision <ArrowRight/></Link></PrototypeButton></div>
      </div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2">
        <div className="panel p-6 md:p-7"><div className="eyebrow">03 / PHYSICAL FEASIBILITY</div><h2 className="mt-2 font-display text-xl font-bold">Vessel & port fit</h2><div className="mt-5 space-y-0 divide-y divide-border">{data.rows.map(row => <div key={row.name} className="flex items-center justify-between gap-3 py-4"><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-sm ${row.feasible ? "bg-secondary text-accent" : "bg-destructive/10 text-destructive"}`}>{row.feasible ? <Check size={17}/> : <CircleAlert size={17}/>}</span><div><div className="text-sm font-semibold">{row.name}</div><div className="text-xs text-muted-foreground">{row.draft}m draft · {row.loa}m LOA · {row.beam}m beam</div></div></div><span className={`text-xs font-bold ${row.feasible ? "text-accent" : "text-destructive"}`}>{row.feasible ? `${row.voyages} voyage${row.voyages > 1 ? "s" : ""}` : "Excluded"}</span></div>)}</div><div className="mt-3 border-t border-border pt-4 text-xs text-muted-foreground">{data.port.name} limits: {data.port.draft}m draft · {data.port.loa}m LOA · {data.port.beam}m beam</div></div>
        <div className="panel p-6 md:p-7"><div className="eyebrow">04 / CONTRACT OPTIONS</div><h2 className="mt-2 font-display text-xl font-bold">Cost versus rate exposure</h2><div className="mt-5 space-y-5">{data.contracts.map(c => <div key={c.name}><div className="mb-2 flex justify-between gap-2 text-sm"><span className="font-medium">{c.name}</span><span className="font-semibold">{compactMoney(c.total)}</span></div><div className="h-2 bg-secondary"><div className="h-2 bg-accent" style={{ width: `${c.total / (data.best?.total ?? c.total) * 88}%` }}/></div><div className="mt-1 text-xs text-muted-foreground">{c.exposure}% relative rate exposure · {c.note}</div></div>)}</div><div className="mt-6 text-xs text-muted-foreground">Pricing premiums and exposure values are illustrative assumptions.</div></div>
      </div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="panel p-6 md:p-7"><div className="eyebrow">05 / SCENARIO WATCHLIST</div><h2 className="mt-2 font-display text-xl font-bold">Worth a closer look</h2><div className="mt-5 divide-y divide-border border-t border-border">{insight.warnings.length ? insight.warnings.map(w => <div key={w.title} className="flex gap-3 py-4"><CircleAlert className="mt-0.5 shrink-0 text-accent" size={18}/><div><div className="text-sm font-semibold">{w.title}</div><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{w.detail}</p></div></div>) : <p className="py-5 text-sm text-muted-foreground">No additional flags under these illustrative assumptions.</p>}</div><p className="mt-3 text-xs text-muted-foreground">Not live alerts or congestion data.</p></section><section className="panel p-6 md:p-7"><div className="eyebrow">06 / WAITING-COST SNAPSHOT</div><h2 className="mt-2 font-display text-xl font-bold">Idle time in the total</h2><div className="mt-5 border-y border-border py-5"><div className="font-display text-3xl font-bold">{data.best ? money(data.best.idle + data.best.demurrage) : "—"}</div><p className="mt-2 text-sm text-muted-foreground">{data.best ? `${(insight.idleShare * 100).toFixed(1)}% of the selected vessel's voyage estimate` : "No feasible vessel for this port"}</p></div><p className="mt-5 text-sm leading-relaxed text-muted-foreground">{insight.alternate ? `For comparison, ${insight.alternate.port.name} assumes ${insight.alternate.port.wait} waiting days. Explore the port switch in your decision report.` : "Compare another destination to understand the waiting-time trade-off."}</p><PrototypeButton asChild variant="outline" className="mt-5"><Link to="/results">Explore what-if comparison <ArrowRight/></Link></PrototypeButton></section></div>
      <section className="panel mt-5 p-6 md:p-7"><div className="eyebrow mb-3">07 / DELIVERY WINDOW</div><ScheduleLens scenario={scenario}/></section>
      <div className="mt-5"><DataAssumptions/></div>
      <div className="mt-5 grid gap-5 md:grid-cols-3">{[{icon:MapPin, title:"Multi-origin sourcing", description:"Compare indicative coal price plus freight across Australia, Indonesia and Mozambique."},{icon:Fuel,title:"Voyage economics",description:"Inspect hire, fuel, port costs, expected idle time and demurrage line by line."},{icon:Compass,title:"Explainable action",description:"See why a vessel fits, what was ruled out and how risk changes the decision."}].map(item => <div key={item.title} className="panel p-6"><item.icon className="text-accent" size={23}/><h3 className="mt-5 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.description}</p></div>)}</div>
      <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-6"><span className="text-sm text-muted-foreground">Change cargo, port, dates and risk settings to explore a different scenario.</span><PrototypeButton asChild><Link to="/new-analysis">Configure shipment <ArrowUpRight/></Link></PrototypeButton></div>
    </div>
  </div>;
}
function Metric({ icon: Icon, label, value, detail, accent = false }: { icon: typeof Ship; label:string; value:string; detail:string; accent?:boolean }) { return <div className="panel min-h-41 p-5"><div className="flex items-center justify-between text-xs font-bold tracking-wider text-muted-foreground"><span>{label}</span><Icon size={18} className="text-accent"/></div><div className={`mt-5 font-display text-3xl font-bold ${accent ? "text-accent" : ""}`}>{value}</div><div className="mt-2 text-xs text-muted-foreground">{detail}</div></div>; }
