import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CalendarDays, CircleAlert, MapPin, Ship, SlidersHorizontal } from "lucide-react";
import { useState, type FormEvent } from "react";
import { PrototypeButton } from "@/components/ui/prototype-button";
import { evaluate, origins, ports, type Scenario } from "@/lib/chartering";
import { useScenario } from "@/lib/scenario-context";
import { ScheduleLens } from "@/components/PlanningAids";
export const Route = createFileRoute("/new-analysis")({ head: () => ({ meta: [{ title: "Plan a Voyage — Charterwise" }, { name: "description", content: "Enter coal cargo, route, dates, contract preference and risk tolerance to explore an illustrative vessel chartering decision." }, { property: "og:title", content: "Plan a Voyage — Charterwise" }, { property: "og:description", content: "Build a shipment scenario and compare feasible vessels, costs and charter options." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: NewAnalysis });
function NewAnalysis() {
  const { scenario, setScenario, setHasRun } = useScenario();
  const [form, setForm] = useState<Scenario>(scenario);
  const [error, setError] = useState("");
  const navigate = useNavigate();
  const update = <K extends keyof Scenario>(key: K, value: Scenario[K]) => setForm(f => ({...f, [key]: value}));
  const result = evaluate(form);
  function submit(e: FormEvent) {
    e.preventDefault();
    if (!form.loadDate || !form.arrivalDate || form.arrivalDate <= form.loadDate) { setError("Arrival must be after your loading date."); return; }
    if (form.quantity < 10000 || form.quantity > 1000000) { setError("Enter a cargo quantity between 10,000 and 1,000,000 tonnes."); return; }
    setError(""); setScenario(form); setHasRun(true); navigate({ to:"/results" });
  }
  return <div className="min-h-[calc(100vh-72px)] bg-secondary pb-20"><div className="border-b border-border bg-background"><div className="shell py-9 md:py-12"><Link to="/dashboard" className="inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft size={15}/> Back to dashboard</Link><div className="eyebrow mt-7">NEW ANALYSIS / SHIPMENT DETAILS</div><h1 className="mt-3 font-display text-3xl font-bold md:text-4xl">Plan a shipment</h1><p className="mt-3 text-sm text-muted-foreground">Set the cargo and route. We’ll check what fits before calculating the voyage.</p></div></div>
  <div className="shell mt-8 grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_320px]"><form onSubmit={submit} className="space-y-5">
    <section className="panel p-6 md:p-8"><Heading number="01" icon={Ship} title="Cargo details" subtitle="Start with the shipment you need to move."/><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Commodity"><select className="field" aria-label="Commodity" value="coal" disabled><option value="coal">Thermal / coking coal</option></select></Field><Field label="Cargo quantity (tonnes)"><input className="field" aria-label="Cargo quantity (tonnes)" type="number" min={10000} max={1000000} step={1000} value={form.quantity} onChange={e => update("quantity", Number(e.target.value))} required/></Field></div><p className="mt-4 text-xs text-muted-foreground">Coal is the supported commodity in this prototype.</p></section>
    <section className="panel p-6 md:p-8"><Heading number="02" icon={MapPin} title="Route & schedule" subtitle="Choose an origin and an East Coast destination."/><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Origin port"><select className="field" aria-label="Origin port" value={form.origin} onChange={e => { const o = origins.find(x => x.id === e.target.value); setForm(f => ({...f, origin:e.target.value, coalPrice:o?.coal ?? f.coalPrice})); }}>{origins.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Destination port"><select className="field" aria-label="Destination port" value={form.destination} onChange={e => update("destination", e.target.value)}>{ports.map(p => <option key={p.id} value={p.id}>{p.name}, India</option>)}</select></Field><Field label="Desired loading date"><input className="field" aria-label="Desired loading date" type="date" value={form.loadDate} onChange={e => update("loadDate", e.target.value)} required/></Field><Field label="Desired arrival date"><input className="field" aria-label="Desired arrival date" type="date" value={form.arrivalDate} onChange={e => update("arrivalDate", e.target.value)} required/></Field></div><div className="mt-7 border-t border-border pt-6"><ScheduleLens scenario={form}/></div></section>
    <section className="panel p-6 md:p-8"><Heading number="03" icon={SlidersHorizontal} title="Decision preferences" subtitle="Adjust the assumptions behind your comparison."/><div className="mt-7 grid gap-6 sm:grid-cols-2"><Field label="Forecast horizon"><div className="flex h-11 border border-input p-1">{[30,60,90].map(n => <PrototypeButton type="button" key={n} variant={form.horizon === n ? "default" : "ghost"} size="sm" className="h-full flex-1 rounded-sm" onClick={() => update("horizon", n)}>{n} days</PrototypeButton>)}</div></Field><Field label="Contract preference"><select className="field" aria-label="Contract preference" value={form.contract} onChange={e => update("contract", e.target.value)}><option value="spot">Compare all · start with spot</option><option value="three">Prefer 3-voyage agreement</option><option value="six">Prefer 6-month agreement</option></select></Field><Field label="Bunker price assumption (USD/t)"><input className="field" type="number" min={100} max={3000} value={form.bunker} onChange={e => update("bunker", Number(e.target.value))}/></Field><Field label="Coal price assumption (USD/t)"><input className="field" type="number" min={1} max={1000} value={form.coalPrice} onChange={e => update("coalPrice", Number(e.target.value))}/></Field></div><div className="mt-7"><div className="flex justify-between text-sm font-semibold"><label htmlFor="risk">Risk tolerance</label><span className="text-accent">{form.risk} / 100</span></div><input id="risk" className="mt-4 w-full accent-accent" type="range" min={0} max={100} value={form.risk} onChange={e => update("risk", Number(e.target.value))}/><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>Conservative</span><span>Flexible</span></div></div></section>
    {error && <p role="alert" className="flex items-center gap-2 text-sm text-destructive"><CircleAlert size={16}/>{error}</p>}
    <div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-md text-xs leading-relaxed text-muted-foreground">All market values, physical limits and pricing assumptions shown here are illustrative and not live quotes.</p><PrototypeButton type="submit" size="lg" className="h-12 px-7">Run analysis <ArrowRight/></PrototypeButton></div>
  </form><aside className="panel p-6 lg:sticky lg:top-6"><div className="eyebrow">SCENARIO PREVIEW</div><h2 className="mt-2 font-display text-xl font-bold">Your route at a glance</h2><div className="mt-6 border-y border-border py-5"><div className="text-xs text-muted-foreground">FROM</div><div className="mt-1 font-semibold">{result.origin.name}</div><div className="my-3 ml-2 h-7 border-l border-dashed border-accent"/><div className="text-xs text-muted-foreground">TO</div><div className="mt-1 font-semibold">{result.port.name}, India</div></div><div className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Cargo</span><span className="font-semibold">{result.quantity.toLocaleString()} t</span></div><div className="flex justify-between"><span className="text-muted-foreground">Approx. distance</span><span className="font-semibold">{result.distance.toLocaleString()} nm</span></div><div className="flex justify-between"><span className="text-muted-foreground">Eligible classes</span><span className="font-semibold">{result.rows.filter(x => x.feasible).length} / 3</span></div><div className="flex justify-between"><span className="text-muted-foreground">Port wait assumption</span><span className="font-semibold">{result.port.wait} days</span></div></div><div className="mt-6 flex gap-3 bg-secondary p-4 text-xs leading-relaxed text-muted-foreground"><CalendarDays size={17} className="shrink-0 text-accent"/><span>Dates and assumptions can be changed any time to explore another scenario.</span></div></aside></div></div>;
}
function Heading({number,icon:Icon,title,subtitle}:{number:string;icon:typeof Ship;title:string;subtitle:string}) { return <div className="flex gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center bg-secondary text-accent"><Icon size={20}/></div><div><div className="text-xs font-bold tracking-wider text-accent">STEP {number}</div><h2 className="mt-1 font-display text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</span>{children}</label>; }
